BLA-16
rainstr7/blade-runners.game pull request #11
Opened 2023-05-04 13:45 UTC by hypnot1z

Добавил страницы форума, роуты, стили
Страница открытого форума, страница темы, создание темы

![BR-Forum](https://user-images.githubusercontent.com/114831001/236224800-79853ea5-3739-4c3c-a74f-4eedb297b7b9.png)

2023-05-05 05:30 UTC, KirGalkin commented on packages/client/src/components/Forum/CreateTheme.module.scss
> +  // padding: 5px;
Лучше закоментированный код сразу удалять, как показывает практика толку от него нет

2023-05-05 05:30 UTC, KirGalkin commented on packages/client/src/components/Forum/CreateTheme.module.scss
> +  // padding: 3px;
также лучше удалить

2023-05-05 05:30 UTC, KirGalkin commented on packages/client/src/components/Forum/CreateTheme.module.scss
> +  font-size: 2rem;
Можно также использовать  в scss вложенность типа
.ThemeHeader {
   h2 {
   }
}

2023-05-05 05:30 UTC, KirGalkin commented on packages/client/src/components/Forum/CreateTheme.tsx
> +  event.preventDefault();
чтото тут явно с форматированием, перед пушем надо сделать 
yarn lint
yarn format

автоматом код отформатирует. надо на досуге будет добавить это в прекоммит

2023-05-05 05:30 UTC, KirGalkin commented on packages/client/src/components/Forum/CreateTheme.tsx
> +    navigate(-1);
мне не нравится -1, я понимаю что это апи, но может подумать и обявить какуюто переменную с понятным именем, но это больше просто на подумать, чем замечание

2023-05-05 05:30 UTC, KirGalkin commented on packages/client/src/components/Forum/CreateTheme.tsx
> +  const newTopic: Topic = {id: nanoid(10), title, messagesCount: 0, messages: []}
гдето ставишь ; а гдето нет. Для это как раз и надо прогонять линтером и претиером

+ закомиченный код и вывод в консоль(если конечно он здесь не нужен по задумке)

2023-05-05 05:30 UTC, KirGalkin commented on packages/client/src/components/Forum/CreateTheme.tsx
> +    <div>
Есть тема как реакт фрагмент, чтобы не плодить лишние div. Это тоже просто на подумать

2023-05-05 05:30 UTC, KirGalkin commented on packages/client/src/components/Forum/Forum.module.scss
> +$Black: rgb(0, 0, 0);
Думаю потом надо будет вынести это в общие стили

2023-05-05 05:30 UTC, KirGalkin commented on packages/client/src/components/Forum/Forum.tsx
> +];
Опять же нет переносов строки

yarn lint
yarn format

2023-05-05 05:30 UTC, KirGalkin commented on packages/client/src/components/Forum/ForumList.module.scss
> +$Black: rgb(0, 0, 0);
вынести

2023-05-05 05:30 UTC, KirGalkin commented on packages/client/src/components/Forum/ForumPage.module.scss
> +$Black: rgb(0, 0, 0);
вынести

2023-05-05 05:30 UTC, KirGalkin commented on packages/client/src/components/Forum/ForumPage.tsx
> +    // если форум с таким id не найден, отображаем страницу ошибки
Отмечай лучше как  
// TODO если форум с таким id не найден, отображаем страницу ошибки
или
// FIXME если форум с таким id не найден, отображаем страницу ошибки

2023-05-05 05:30 UTC, KirGalkin commented on packages/client/src/components/Forum/ThemePage.module.scss
> +  // background-image: url('../../assets/mava.jpg');
удалить

2023-05-05 05:30 UTC, KirGalkin commented on packages/client/src/components/Forum/ThemePage.tsx
> +// import ava from '../../assets/ava.png'
удалить

2023-05-05 05:30 UTC, KirGalkin commented on packages/client/src/components/Forum/ThemePage.tsx
> +  function removePathSuffix(path: string): string {
кажется можно вынести из компонента

2023-05-05 05:30 UTC, KirGalkin commented on packages/client/src/components/Forum/ThemePage.tsx
> +  const { id } = useParams<{ id: string }>();
yarn lint
yarn format

2023-05-05 05:30 UTC, KirGalkin commented on packages/client/src/components/Forum/ThemePage.tsx
> +  const [state, setState] = React.useState(messages)
Для обсуждения, я обычно хуки определяю в начале компонента

2023-05-05 05:45 UTC, KirGalkin commented on packages/client/src/components/Forum/CreateTheme.tsx
> +import styles from './CreateTheme.module.scss'
Это чисто вкусовщина, но у нас везде начали использовать аббревиатуру cn(class names)

2023-05-05 10:11 UTC, rainstr7 commented on packages/client/src/components/Forum/ThemePage.tsx
> +  const [state, setState] = React.useState(messages)
хуки всегда идут вначале компонента это важно

2023-05-05 14:26 UTC, hypnot1z commented
Временно закоментил nanoid

2023-05-06 13:54 UTC, rainstr7 commented
Еще нужно ресолвить конфликт

2023-05-06 16:03 UTC, rainstr7 approved these changes

2023-05-06 16:03 UTC, rainstr7 approved these changes

2023-05-07 19:48 UTC, kate-lozovaya commented
От `fix` `fix` `fix` коммитов спасет `git rebase -i HEAD~<количество_коммитов>`, где эти коммиты можно склеить, и история коммитов будет красивая
<img width="200" alt="image" src="https://user-images.githubusercontent.com/25737137/236699370-cdf24430-b2f2-417d-9141-9d546bc5645b.png">

2023-05-07 20:26 UTC, kate-lozovaya requested changes
По формату комментов. Использую [Исправление], [Предложение], [Вопрос]
[Исправление] пишу там, где прям очень хочется увидеть исправление, но всегда можно все обсудить )
И хочется увидеть после ревью обработку каждого коммента от тебя. Можно писать текстом, можно ставить смайлики, резолвить мне удобнее самой, чтобы пройтись глазами, и посмотреть на код еще раз.

Посмотри еще, пожалуйста, на комментарии ребят, чтобы все они были обработаны и зарезолвлены.

Так же как и в другом ПР, что я смотрела не видно текст в инпутах.
<img width="400" alt="image" src="https://user-images.githubusercontent.com/25737137/236701032-57bbcf6b-742b-4a24-b027-f89c3a459544.png">

2023-05-07 20:26 UTC, kate-lozovaya commented on packages/client/src/components/Forum/CreateTheme.tsx
> +        <input
[Предложение]
В проекте есть компонент [Input](https://github.com/rainstr7/blade-runners.game/tree/dev/packages/client/src/components/UI/Input). Может его использовать тут?

2023-05-07 20:26 UTC, kate-lozovaya commented on packages/client/src/components/Forum/CreateTheme.tsx
> +        <h2>topic.title</h2>
[Вопрос]
Выглядит как переменная без фигурных скобок, но переменной topic тут нет.
Тут точно все так, как должно быть?

2023-05-07 20:26 UTC, kate-lozovaya commented on packages/client/src/components/Forum/Forum.module.scss
> +    }
[Исправление]
Ховер лучше выносить в media запрос, чтобы на телефоне не нужно было делать два клика для отклика от кнопки. Я обычно пишу `@media (hover: hover) and (pointer: fine)`, в [doka пишут](https://doka.guide/css/hover/) про `any-hover: hover`

2023-05-07 20:26 UTC, kate-lozovaya commented on packages/client/src/components/Forum/Forum.tsx
> +]
[Предложение]
Можно вынести в моки

2023-05-07 20:26 UTC, kate-lozovaya commented on packages/client/src/components/Forum/ForumList.tsx
> +    <div>
[Предложение]
Можно использовать фрагмент `<></>`

2023-05-07 20:26 UTC, kate-lozovaya commented on packages/client/src/components/Forum/ForumPage.tsx
> +  }
[Предложение]
Может положить функции рядом с компонентом с роутами? Сейчас если в `Forum.tsx` поменяется какой-то роут, придется идти по нескольким файлам и править пути

2023-05-07 20:26 UTC, kate-lozovaya commented on packages/client/src/components/Forum/ForumPage.tsx
> +    <div>
[Предложение]
Можно заменить на фрагмент

2023-05-07 20:26 UTC, kate-lozovaya commented on packages/client/src/components/Forum/ThemePage.tsx
> +        />
[Предложение]
Можно заменить на компонент Input, который есть в проекте

2023-05-07 20:26 UTC, kate-lozovaya commented on packages/client/src/components/Forum/ThemePage.tsx
> +    <div>
[Предложение]
Можно заменить на фрагмент

2023-05-07 20:26 UTC, kate-lozovaya commented on packages/client/src/components/Forum/ThemePage.tsx
> +          <div className={cn.Msg} key={message.id}>
[Предложение]
Может тут можно использовать section?

2023-05-08 08:08 UTC, hypnot1z commented on packages/client/src/components/Forum/ThemePage.tsx
> +    <div>
![готово](https://flyclipart.com/thumb2/green-check-mark-clip-art-411285.png)

2023-05-08 08:10 UTC, hypnot1z commented on packages/client/src/components/Forum/ThemePage.tsx
> +    <div>
`#0BDA51`

2023-05-08 08:14 UTC, hypnot1z commented on packages/client/src/components/Forum/ForumPage.tsx
> +    <div>
- [x] Готово

2023-05-08 08:15 UTC, hypnot1z commented on packages/client/src/components/Forum/ForumList.tsx
> +    <div>
- [x] Готово

2023-05-08 08:25 UTC, hypnot1z commented on packages/client/src/components/Forum/Forum.module.scss
> +    }
- [x] Готово, почитал doka, использовал any-hover

2023-05-08 10:10 UTC, hypnot1z commented on packages/client/src/components/Forum/ThemePage.tsx
> +          <div className={cn.Msg} key={message.id}>
- [x] Готово

2023-05-08 11:13 UTC, hypnot1z commented on packages/client/src/components/Forum/CreateTheme.tsx
> +        <h2>topic.title</h2>
- [x] Пока так, после добавления Стэйта там будет название текущего форума

2023-05-08 11:41 UTC, hypnot1z commented on packages/client/src/components/Forum/CreateTheme.tsx
> +        <input
- [x] Попробовал. Преимуществ не добавляет, стили ломаются, оставил стандартный

2023-05-08 11:41 UTC, hypnot1z commented on packages/client/src/components/Forum/ThemePage.tsx
> +        />
- [x] Попробовал. Преимуществ не добавляет, стили ломаются, оставил стандартный

2023-05-08 12:24 UTC, hypnot1z commented on packages/client/src/components/Forum/ThemePage.tsx
> +    return <div>Тема не найден</div>
- [x] ok

2023-05-08 12:24 UTC, hypnot1z commented on packages/client/src/components/Forum/ForumPage.module.scss
> +  text-decoration: none;
- [x] ok

2023-05-08 12:25 UTC, hypnot1z commented on packages/client/src/components/Forum/ForumPage.module.scss
> +  padding-bottom: 20px;
- [x] ok

2023-05-08 12:26 UTC, hypnot1z commented on packages/client/src/components/Forum/ForumList.tsx
> +  }
- [x] ok

2023-05-08 12:26 UTC, hypnot1z commented on packages/client/src/components/Forum/ForumList.module.scss
> +}
- [x] ok

2023-05-08 12:26 UTC, hypnot1z commented on packages/client/src/components/Forum/ForumList.module.scss
> +  padding-top: 20px;
- [x] ok

2023-05-08 12:26 UTC, hypnot1z commented on packages/client/src/components/Forum/Forum.tsx
> +import { CreateTheme } from './CreateTheme'
- [x] ok

2023-05-08 12:26 UTC, hypnot1z commented on packages/client/src/components/Forum/Forum.tsx
> +import * as React from 'react'
- [x] ok

2023-05-08 12:26 UTC, hypnot1z commented on packages/client/src/App.tsx
> +import { Forum } from './components/Forum/Forum'
- [x] ok

2023-05-08 12:27 UTC, hypnot1z commented on packages/client/src/components/Forum/ForumList.module.scss
> +  background-color: white;
- [x] цветы ок

2023-05-08 12:28 UTC, hypnot1z commented on packages/client/src/components/Forum/ForumList.module.scss
> +}
- [x] ok

2023-05-08 12:45 UTC, hypnot1z commented on packages/client/src/components/Forum/ForumList.module.scss
> +  width: 120px;
Лучше объяснять, без этого не убедительно.

2023-05-08 12:45 UTC, hypnot1z commented on packages/client/src/components/Forum/CreateTheme.tsx
> +import styles from './CreateTheme.module.scss'
- [x] ok

2023-05-08 12:46 UTC, hypnot1z commented on packages/client/src/components/Forum/ThemePage.tsx
> +  const [state, setState] = React.useState(messages)
- [x] ok

2023-05-08 12:46 UTC, hypnot1z commented on packages/client/src/components/Forum/ThemePage.tsx
> +  const { id } = useParams<{ id: string }>();
- [x] ok

2023-05-08 12:47 UTC, hypnot1z commented on packages/client/src/components/Forum/ThemePage.tsx
> +// import ava from '../../assets/ava.png'
- [x] ok

2023-05-08 12:47 UTC, hypnot1z commented on packages/client/src/components/Forum/ThemePage.module.scss
> +  // background-image: url('../../assets/mava.jpg');
- [x] ok

2023-05-08 12:48 UTC, hypnot1z commented on packages/client/src/components/Forum/CreateTheme.tsx
> +    navigate(-1);
- [x] Пока так.

2023-05-08 12:48 UTC, hypnot1z commented on packages/client/src/components/Forum/CreateTheme.tsx
> +  event.preventDefault();
- [x] ok

2023-05-08 12:48 UTC, hypnot1z commented on packages/client/src/components/Forum/CreateTheme.module.scss
> +  font-size: 2rem;
- [x] ok

2023-05-08 12:48 UTC, hypnot1z commented on packages/client/src/components/Forum/CreateTheme.module.scss
> +  // padding: 3px;
- [x] ok

2023-05-08 12:48 UTC, hypnot1z commented on packages/client/src/components/Forum/CreateTheme.module.scss
> +  // padding: 5px;
- [x] ok

2023-05-08 16:52 UTC, kate-lozovaya commented on packages/client/src/components/Forum/CreateTheme.tsx
> +        <input
Компонент в проекте должен быть расширяемым, чтобы ты мог положить его в `div`, и через него добавить нужные стили, либо прокинуть их в сам компонент.

Преимущество - изменение в одном месте при изменении дизайна. Например, дизайнер решит, что у инпутов должна быть новая тень, и нужно пойти и поменять только `Input`, если везде будет использоваться он. А с текущей реализацией нужно будет  пойти и в Input, плюс пройтись по всему коду и найти все использования input, поменять и их тоже

2023-05-08 16:52 UTC, kate-lozovaya commented on packages/client/src/components/Forum/Forum.tsx
> +]
Почему? Компонент получается очень длинный, трудно его читать. И когда моки заменятсяна апи, в этом файле будет большой и неудобночитаемый диф

2023-05-08 19:58 UTC, hypnot1z commented on packages/client/src/components/Forum/CreateTheme.tsx
> +        <input
- [x] Добавил. Но не убедился в правильности этого решения. Например, дизайнер решит изменить стиль форума, а форма авторизации/регистрации останется прежней. Придется идти искать эти инпуты... Решение, которое мне кажется, самым логичным, это использовать единый инпут для авторизации/регистрации, редактирования профиля (да, тут оправдано, и единый стиль и повторяемость и изменяемость если нужно). А для форума с двумя инпутами, которые могут кардинально отличаться, не вижу смысла использовать единый инпут. Я могу, конечно, ошибаться, большого опыта в этом деле не имею.

2023-05-08 20:12 UTC, hypnot1z commented on packages/client/src/components/Forum/Forum.tsx
> +]
-[x] Вынес в отдельный файл, не понял куда "правильно" его поместить.

2023-05-08 20:13 UTC, hypnot1z commented on packages/client/src/components/Forum/ThemePage.tsx
> +        />
- [x] Добавил

2023-05-08 20:16 UTC, hypnot1z commented on packages/client/src/components/Forum/CreateTheme.tsx
> +    <div>
- [x]

2023-05-08 20:48 UTC, hypnot1z commented on packages/client/src/components/Forum/ForumList.module.scss
> +$Black: rgb(0, 0, 0);
- [x] Ok

2023-05-08 20:48 UTC, hypnot1z commented on packages/client/src/components/Forum/ForumPage.module.scss
> +$Black: rgb(0, 0, 0);
- [x] Ok

2023-05-09 13:07 UTC, kate-lozovaya commented on packages/client/src/components/Forum/Forum.tsx
> +]
Удобно использовать папку `mocks`, в которой будут все моки для страницы, файл можно назвать как-то так `<данные_для_форума>.mock.ts`

2023-05-09 13:08 UTC, kate-lozovaya approved these changes

2023-05-09 13:08 UTC, kate-lozovaya commented on packages/client/src/components/Forum/types.ts
👍🏻

2023-05-09 13:11 UTC, kate-lozovaya commented on packages/client/src/components/Forum/CreateTheme.tsx
> +        <input
У дизайнера есть склад всех компонентов, он не должен использовать кардинально новые для другой страницы, потому что везде должен быть единый стиль

2023-05-10 20:19 UTC, merged