Bla 21
rainstr7/blade-runners.game pull request #13
Opened 2023-05-04 22:20 UTC by OvalniyKeks

Вёрстка страницы профиля

- Добавил страницу профиля
- Убрал из дефолтных стилей инпута margin-bottom

![image](https://user-images.githubusercontent.com/106172681/236341796-376b68c6-0e50-4876-87df-f8a89ba457ed.png)

2023-05-06 10:03 UTC, hypnot1z approved these changes
Отлично! Хорошая работа!

2023-05-06 13:12 UTC, rainstr7 commented on packages/client/src/components/UI/Avatar/index.tsx
> +    <div className={`${cn.avatar} ${avatarSize}`} style={{backgroundImage: `url(${props.src})`}}></div>
я кстати прям компонент сделал Avatar потом можно оставить один и переиспользовать

2023-05-06 13:12 UTC, rainstr7 commented on packages/client/src/components/UI/Avatar/style.module.scss
> +    width: 60px;
лучше использовать относительные единицы rem 60px === 3rem

2023-05-06 13:12 UTC, rainstr7 commented on packages/client/src/components/UI/Avatar/style.module.scss
> +  background-repeat: no-repeat;
по моему мы несколько раз используем одинаковый набор стилей для background можно вынести в миксин?

2023-05-06 13:12 UTC, rainstr7 commented on packages/client/src/components/UI/ButtonLink/index.tsx
> +  to?: string,
а зачем запятая? я всегда думал в interface точка с запятой в конце) но почему именно у to запятая появилась?

2023-05-06 13:12 UTC, rainstr7 commented on packages/client/src/components/UI/CardLink/index.tsx
> +export default CardLink
есть компонент ButtonLink он принципиально отличается как то? или это чтобы оборачивать в ссылку ? можно через click отправлять на другую страницу через router api ну это тоже на подумать

2023-05-06 13:12 UTC, rainstr7 commented on packages/client/src/views/Profile/style.module.scss
> +  justify-content: center;
тут тоже   
display: flex;
 justify-content: center;

2023-05-06 13:14 UTC, rainstr7 commented
Написал комменты все обсуждаемо, отпишись плиз согласен не согласен

2023-05-06 16:02 UTC, rainstr7 approved these changes

2023-05-07 12:09 UTC, OvalniyKeks commented on packages/client/src/components/UI/Avatar/index.tsx
> +    <div className={`${cn.avatar} ${avatarSize}`} style={{backgroundImage: `url(${props.src})`}}></div>
👍

2023-05-07 12:14 UTC, OvalniyKeks commented on packages/client/src/components/UI/Avatar/style.module.scss
> +  background-repeat: no-repeat;
👍 Вынес

2023-05-07 12:16 UTC, OvalniyKeks commented on packages/client/src/views/Leaderboard/style.module.scss
> +  font-size: 32px;
👍 да можно в задачу отдельную вынести

2023-05-07 12:19 UTC, OvalniyKeks commented on packages/client/src/views/Profile/index.tsx
> +  const [profileData, setprofileData] = useState({})
fix

2023-05-07 12:20 UTC, OvalniyKeks commented on packages/client/src/views/Profile/style.module.scss
> +}
fix

2023-05-07 12:24 UTC, OvalniyKeks commented on packages/client/src/views/Profile/style.module.scss
> +}
Пофиксил, добавил миксин flex-horizontal-center, а насчет колонок, то при адаптиве можно просто прописать в media стилях grid-templates-column: 1fr, тут грид затем,чтобы можно было выставить одинаковые отступы между инпутами

2023-05-07 12:25 UTC, OvalniyKeks commented on packages/client/src/views/Profile/style.module.scss
> +  justify-content: center;
fix

2023-05-07 19:40 UTC, kate-lozovaya requested changes
По формату комментов. Использую [Исправление], [Предложение], [Вопрос]
[Исправление] пишу там, где прям очень хочется увидеть исправление, но всегда можно все обсудить )
И хочется увидеть после ревью обработку каждого коммента от тебя. Можно писать текстом, можно ставить смайлики, резолвить мне удобнее самой, чтобы пройтись глазами, и посмотреть на код еще раз.


Попыталась ввести текст, а его не видно (приложила скрин). 
И страница не скролится, к сабмиту можно придти только через tab
<img width="450" alt="image" src="https://user-images.githubusercontent.com/25737137/236698715-9c110cc6-0cd8-4c53-9384-ea2b8b4de313.png">

2023-05-07 19:40 UTC, kate-lozovaya commented on packages/client/src/views/Profile/style.module.scss
> +.formWrapper {
[Исправление]
Высота этого элемента получается больше, чем у profile, из-за этого нельзя поскролить к кнопке сабмита
<img width="400" alt="image" src="https://user-images.githubusercontent.com/25737137/236699004-f5a0491b-0c76-4b12-83bc-22b28b643b16.png">

2023-05-07 19:40 UTC, kate-lozovaya commented on packages/client/src/views/Profile/index.tsx
> +const ProfileFormData = [
[Предложение]
Хочется в tsx файле видеть маленький компонент, который легко прочитать. Может вынести `ProfileFormData`, `phoneRegExp`, `schema`?

2023-05-08 12:09 UTC, OvalniyKeks commented on packages/client/src/views/Profile/style.module.scss
> +.formWrapper {
Верстку пофиксил, теперь видно все, по тексту, к сожалению шрифт не поддерживает кириллицу

2023-05-08 12:10 UTC, OvalniyKeks commented on packages/client/src/views/Profile/index.tsx
> +const ProfileFormData = [
Да было бы круто вынести валидацию формы, вот только я не знаю куда) На vue я бы вынес это в utils, но с реактом до этого момента не работал, куда лучше вынести? Создать отдельный hook?

2023-05-08 12:59 UTC, kate-lozovaya commented on packages/client/src/views/Profile/style.module.scss
> +.formWrapper {
Скроллить все равно не получается
<img width="400" alt="image" src="https://user-images.githubusercontent.com/25737137/236830496-5f67b84a-085e-4692-b62c-9eacc4ec4f3c.png">

2023-05-08 13:03 UTC, kate-lozovaya requested changes
Скролл все равно не работает, кнопка для сабмита не видна

2023-05-08 13:03 UTC, kate-lozovaya commented on packages/client/src/components/Layout/index.tsx
> +        <div className={cn.Authors}>BY blade runners</div>
[Предложение]
Лучше использовать тег `p` для текста

2023-05-10 15:40 UTC, OvalniyKeks commented on packages/client/src/views/Profile/style.module.scss
> +.formWrapper {
Добавил виртуальный скролл

2023-05-10 15:40 UTC, OvalniyKeks commented on packages/client/src/components/Layout/index.tsx
> +        <div className={cn.Authors}>BY blade runners</div>
Пофиксил, скролл работает

2023-05-10 17:00 UTC, kate-lozovaya approved these changes
👍🏻 
В следующий раз лучше еще раз призывай для ревью, чтобы в гитхабе было видно, что на меня что-то назначено

2023-05-10 18:11 UTC, merged