Bla 28
rainstr7/blade-runners.game pull request #22
Opened 2023-05-22 13:33 UTC by OvalniyKeks

Реализовано начало и завершение игры

- Добавил стартовый отсчет
- Добавил переключение на страницу gameover при геймовере
- Добавил вывод полученных очков на страницу gameover

![image](https://github.com/rainstr7/blade-runners.game/assets/106172681/57e34a66-0228-469c-97f0-8342261f4f13)
![image](https://github.com/rainstr7/blade-runners.game/assets/106172681/04e56ec3-c612-47e1-b18b-1306707a7d78)

2023-05-22 16:40 UTC, KirGalkin commented on packages/client/src/App.tsx
> +          <Route path="/gameover" element={<GameOver changeLayout={changeLayout} />} />
changeLayout={changeLayout} вот этого вроде не надо

2023-05-22 16:40 UTC, KirGalkin commented on packages/client/src/core/engine.ts
> +    ctx.fillStyle = "#00000070";
Это цвет такой?

2023-05-22 17:29 UTC, OvalniyKeks commented on packages/client/src/core/engine.ts
> +    ctx.fillStyle = "#00000070";
Это черный с прозрачностью 70%)

2023-05-22 17:31 UTC, OvalniyKeks commented on packages/client/src/App.tsx
> +          <Route path="/gameover" element={<GameOver changeLayout={changeLayout} />} />
Там компонент GameOver требует, так как у него layout не дефолтный

2023-05-23 04:05 UTC, KirGalkin approved these changes

2023-05-23 07:42 UTC, rainstr7 commented on packages/client/src/App.tsx
> +          <Route path="/gameover" element={<GameOver changeLayout={changeLayout} />} />
здесь props changeLayout не нужен - так же во всех остальных (но в остальных я уже отрефакторил) можешь посмотреть код у меня https://github.com/rainstr7/blade-runners.game/blob/BLA-33/packages/client/src/App.tsx

2023-05-23 07:42 UTC, rainstr7 commented on packages/client/src/core/GameLayout/index.tsx
> +const GameLayout = ({changeScore}: any) => {
ну тут бы типизировать any я в скриншоте поставил чтобы время не тратить на типизацию

2023-05-23 07:42 UTC, rainstr7 commented on packages/client/src/core/engine.ts
> +  game = async (ctx: CanvasRenderingContext2D, deltaTime: number) => {
а зачем тут async?  если нигде нет await

2023-05-23 10:08 UTC, OvalniyKeks commented on packages/client/src/core/GameLayout/index.tsx
> +const GameLayout = ({changeScore}: any) => {
Переделал на хуки, больше этого кода нет

2023-05-23 12:39 UTC, rainstr7 approved these changes

2023-05-24 06:57 UTC, kate-lozovaya requested changes

2023-05-24 06:57 UTC, kate-lozovaya commented on packages/client/src/store/reduces/scoreReducer.ts
> +export default function scoreReducer(state = initialState, action: any) {
[Исправление]
Почему тут any? Посмотрела, что в других редьюсорах используется ActionInterface. Лучше их сделать едиными, и не использовать any

2023-05-24 14:49 UTC, kate-lozovaya approved these changes

2023-05-24 14:49 UTC, kate-lozovaya approved these changes

2023-05-24 18:36 UTC, merged