Bla 27
rainstr7/blade-runners.game pull request #23
Opened 2023-05-22 16:28 UTC by KirGalkin

Реализована одна из игровых механик, описанных в документе с логикой игры.
https://linear.app/blade-runners/issue/BLA-27/realizovana-odna-iz-igrovyh-mehanik-opisannyh-v-dokumente-s-logikoj

В данном ПР сделано
- Вынес состояние игрока в отдельные классы, рефакторинг
- Вынес противников в отдельные классы, рефакторинг
- Теперь прыжок зависит от нажатия
- Добавил Paralax Background
- Игра ускоряется
- Рефакторинг

<img width="1037" alt="image" src="https://github.com/rainstr7/blade-runners.game/assets/124124244/ac75597a-ef75-476c-970a-0d238d4b6b1f">

2023-05-22 18:03 UTC, OvalniyKeks approved these changes
Там отметил по мелочи, что мб лучше в прод не заливать, а так топчик) поиграл, работает круто)

2023-05-22 18:03 UTC, OvalniyKeks commented on packages/client/src/core/playerStates.ts
> +    console.log('RunningState')
Мб лучше убрать

2023-05-22 18:03 UTC, OvalniyKeks commented on packages/client/src/core/playerStates.ts
> +    console.log('JumpingState')
Тут тоже мб лучше убрать

2023-05-22 18:03 UTC, OvalniyKeks commented on packages/client/src/core/playerStates.ts
> +    console.log('FallingState')
тут тоже console.log

2023-05-22 18:03 UTC, OvalniyKeks commented on packages/client/src/core/playerStates.ts
> +    console.log(this.player.yV)
И тут

2023-05-23 15:07 UTC, kate-lozovaya requested changes

2023-05-23 15:07 UTC, kate-lozovaya commented on packages/client/src/core/engine.ts
> +      switch (enemyType) {
[Предложение]
Может тут сделать объект?
```
const enemies: Record<0 | 1 | 2, Enemy> = {
  0: new GroundEnemy(...),
  ...
}
```

Тогда можно будет в переменную записывать сразу тип `Enemy`:
`const enemy: Enemy = enemies[enemyType]`
И в `this.enemies.push(enemy as Enemy)` можно будет избавиться от `as`

2023-05-24 04:28 UTC, KirGalkin commented on packages/client/src/core/background.ts
> +class Layer {
Тогда его нужно будет отдельно экспортировать, а я бы хотел чтобы он остался просто служебным закрытым классом

2023-05-24 04:41 UTC, KirGalkin commented on packages/client/src/core/engine.ts
> +      switch (enemyType) {
Согласен, но пришлось сделать вот так
```
      const enemyType = randomFromInterval(0, 2) as 0 | 1 | 2

      const enemyByType: Record<0 | 1 | 2, Enemy> = {
```

2023-05-24 06:37 UTC, kate-lozovaya commented on packages/client/src/core/background.ts
> +class Layer {
Я классы на работе не использую, пишу функции, их нравится уносить вниз под основной компонент, чтобы сразу вверху файла была вся суть написана

2023-05-24 06:40 UTC, kate-lozovaya requested changes

2023-05-24 06:40 UTC, kate-lozovaya commented on packages/client/src/core/engine.ts
> +      const enemyByType: Record<0 | 1 | 2, Enemy> = {
[Исправление]
Лучше создать тип `type EnemyType = 0 | 1 | 2`
Тогда тут будет так:
```suggestion
      const enemyType: EnemyType = randomFromInterval(0, 2)

      const enemyByType: Record<EnemyType, Enemy> = {
```

2023-05-24 06:41 UTC, kate-lozovaya commented on packages/client/src/core/engine.ts
> +      switch (enemyType) {
Моно сделать тип `type EnemyType = 0 | 1 | 2`

2023-05-25 04:25 UTC, KirGalkin commented on packages/client/src/core/engine.ts
> +      const enemyByType: Record<0 | 1 | 2, Enemy> = {
Сделал, но от as все равно не получилось избавится :( 
тк randomFromInterval возвращает  просто number и TS ругается что
 Type 'number' is not assignable to type 'EnemyType'.
```
      const enemyType: EnemyType = randomFromInterval(0, 2) as EnemyType

      const enemyByType: Record<EnemyType, Enemy> = { 
```

2023-05-26 18:25 UTC, kate-lozovaya commented on packages/client/src/core/engine.ts
> +      const enemyByType: Record<0 | 1 | 2, Enemy> = {
Оберни `randomFromInterval(0, 2)` в функцию, которая будет возвращать `EnemyType`. Использование as = выключить TS, так лучше не делать

2023-05-27 06:30 UTC, kate-lozovaya approved these changes

2023-05-27 11:29 UTC, KirGalkin commented on packages/client/src/core/engine.ts
> +      const enemyByType: Record<0 | 1 | 2, Enemy> = {
<img width="630" alt="image" src="https://github.com/rainstr7/blade-runners.game/assets/124124244/4b696b65-97b6-4b44-b780-4d931a89238a">

Я видимо чтото не понимаю?

2023-05-27 11:31 UTC, merged