Bla 14
rainstr7/blade-runners.game pull request #3
Opened 2023-04-27 11:42 UTC by rainstr7

### Базовая подготовка проекта
- Подключение шрифтов и базовая разметка HTML;
- Подключения файла reset css для сброса базовых стилей;
- Создание базовой разметки;
- Подключение SASS (Добавление зависимости);
- Создание файла с переменными vars.scss;
- Добавление favicon.ico;
- Добавление <title>;

### Вёрстка страницы логина
Создание страницы ввода логина и пароля

### Скриншот
![Screenshot 2023-04-27 at 14 34 54](https://user-images.githubusercontent.com/42678580/234851662-b5752885-e27a-4b6d-b273-a50cc423c1d8.png)

2023-04-30 07:50 UTC, rainstr7 commented
в последнем комите пересмотрел подход к компоненту Layout, добавил background для game over

2023-04-30 12:30 UTC, KirGalkin commented on packages/client/src/views/Auth/index.tsx
> +  const [authData, setAuthData] = useState({ login: '', password: '' })
Смущает нэйминг, что за values непонятно, кажется лучше разнести на
const [login, setLogin] =....
const [password, setPassword] =....

ну либо както const [authData, setAuthData]

2023-04-30 16:31 UTC, rainstr7 commented on packages/client/src/components/UI/Input/index.tsx
> +const Input = ({ placeholder, type, value, name, onChange, autoComplete='off' }: Props) => {
исправил в новых коммитах

2023-04-30 16:31 UTC, rainstr7 commented on packages/client/src/views/Auth/index.tsx
> +  const [values, setValue] = useState({ login: '', password: '' })
исправил в новых комитах

2023-04-30 16:32 UTC, rainstr7 commented on packages/client/src/views/Auth/index.tsx
> +    <div className={cn.Container}>
div это тег, или ты имеешь ввиду семантические теги  HTML5?

2023-04-30 16:33 UTC, rainstr7 commented on packages/client/src/views/Auth/index.tsx
> +  const [authData, setAuthData] = useState({ login: '', password: '' })
тут нет уже values

2023-04-30 19:25 UTC, KirGalkin approved these changes
Хорошо оформлен)

2023-04-30 21:54 UTC, OvalniyKeks approved these changes
👍

2023-05-02 14:28 UTC, kate-lozovaya requested changes
По формату комментов. Использую [Исправление], [Предложение], [Вопрос]
[Исправление] пишу там, где прям очень хочется увидеть исправление, но всегда можно все обсудить )

И хочется увидеть после ревью обработку каждого коммента от тебя. Можно писать текстом, можно ставить смайлики, резолвить мне удобнее самой, чтобы пройтись глазами, и посмотреть на код еще раз.


Было бы еще здорово сделать автодеплой. [Вот тут](https://github.com/yandex-praktikum/client-server-template-with-vite#автодеплой-статики-на-vercel) написано как, чтобы можно было зайти и покликать самой.
Но это отдельная задача.

2023-05-02 14:28 UTC, kate-lozovaya commented on packages/client/src/components/UI/Header/index.tsx
> +  return <h1 className={cn.Header}>{title}</h1>
[Вопрос]
А такой компонент точно нужен? 
В нем ведь нельзя настроить уровень заголовка. Выглядит так, будто он будет использоваться всего пару раз, и придется создавать аналогичные компоненты для остальных уровней заголовков.

Можно сделать что-то вроде [typography](https://mui.com/material-ui/react-typography/).
У меня в проекте используется отдельный css файл со всеми возможными шрифтами, и они просто как классы добавляются компонентам.

2023-05-02 14:28 UTC, kate-lozovaya commented on packages/client/src/components/HOC/Layout/style.module.scss
> +    text-decoration: none;
[Вопрос]
А это правило только для ссылок в `Layout`? Его не нужно добавить в `reset.css`?

2023-05-02 14:28 UTC, kate-lozovaya commented on packages/client/src/components/HOC/Layout/style.module.scss
> +    outline: none;
[Вопрос]
Тут тоже вопрос про `reset.css`. Это правило не нужно туда перенести? 

И если нет `outline`, будет ли видно, на каком `input` сейчас находится пользователь при перемещении по элементам клавиатурой?

2023-05-02 14:28 UTC, kate-lozovaya commented on packages/client/src/views/Auth/index.tsx
> +  const [authData, setAuthData] = useState({ login: '', password: '' })
[Предложение]
Тут бы тип написать `useState<Type>`

2023-05-02 15:00 UTC, rainstr7 commented on packages/client/src/styles/mixins.scss
> +@mixin flex-center {
ну да, я думаю mixin-ы будут добавляться я просто сделал как надо было мне

2023-05-02 15:03 UTC, rainstr7 commented on packages/client/src/components/UI/Button/index.tsx
> +      {label}
справедливо - исправил, спасибо

2023-05-02 15:06 UTC, rainstr7 commented on packages/client/src/components/UI/Button/index.tsx
> +interface Props {
справедливо - исправил, спасибо

2023-05-02 15:35 UTC, rainstr7 commented on packages/client/src/components/UI/ButtonLink/style.module.scss
> +.ButtonLink {
не думал пока особо об анимации, но прикрутил transition

2023-05-02 15:36 UTC, rainstr7 commented on packages/client/src/components/UI/Header/index.tsx
> +  return <h1 className={cn.Header}>{title}</h1>
Я думаю он будет расширяться по мере использования. У меня нет задачи написать универсальную UI библиотеку типа MUI )

2023-05-02 15:44 UTC, rainstr7 commented on packages/client/src/components/HOC/Layout/style.module.scss
> +    outline: none;
я сделал так чтобы цвет у a подхватывался из переменной но подумал теперь что можно обыграть inherit

2023-05-02 16:31 UTC, rainstr7 commented
https://blade-runners-game-client.vercel.app/ настроил vercel

2023-05-03 07:52 UTC, kate-lozovaya commented on packages/client/src/styles/mixins.scss
> +@mixin flex-center {
Я когда читаю слово center, ожидаю, что это будет центр по всем осям. Посоветуйся с ребятами, всем ли удобен такой нейминг и свойства

2023-05-03 07:56 UTC, kate-lozovaya commented on packages/client/src/components/UI/Button/index.tsx
> +interface Props {
Скорее всего еще появится параметр `appearence`, например, для стиля кнопки, чтобы делать ее для темной и светлой темы. И получится что-то такое:
```
interface Props {
  appearence: ButtonAppearence
} & ButtonHTMLAttributes<HTMLButtonElement>
```
Но это можно будет потом добавить, если понадобится

2023-05-03 08:13 UTC, kate-lozovaya commented on packages/client/src/components/UI/Header/index.tsx
> +  return <h1 className={cn.Header}>{title}</h1>
Мне кажется, что такой компонент вообще не нужен. Будто бы можно просто сделать css со шрифтами, и подключать их через классы на страницах

2023-05-03 08:15 UTC, kate-lozovaya commented on packages/client/src/views/Auth/index.tsx
> +  const [authData, setAuthData] = useState({ login: '', password: '' })
явное лучше неявного ) 
всегда может кто-то придти и что-то поменять, лучше обезопасить стейт

2023-05-03 08:19 UTC, rainstr7 commented on packages/client/src/styles/mixins.scss
> +@mixin flex-center {
создал опросник в чате и на всякий случай переименовал

2023-05-03 08:21 UTC, kate-lozovaya approved these changes

2023-05-03 09:47 UTC, merged