Bla 49
rainstr7/blade-runners.game pull request #34
Opened 2023-06-21 12:23 UTC by rainstr7

### Какую задачу решаем
Эмодзи (клиентская часть)

Добавлены 
Добавление/удаление эмоции
Добавление/удаление топика
Добавление/удаление (только своего) сообщения
Полностью переработан раздел форум - переписан на Redux
Реализовал хук для обмена информации, сейчас он общается с редаксом - но после реализации бек части будет получать данные через бекенд и добавлять в редакс уже респонс
Добавил немного красоты

### Скриншоты/видяшка (если есть)
![Screenshot 2023-06-21 at 14 52 56](https://github.com/rainstr7/blade-runners.game/assets/42678580/4ae03aba-2992-430a-a202-034e178070cf)
![Screenshot 2023-06-21 at 14 55 00](https://github.com/rainstr7/blade-runners.game/assets/42678580/55b3561f-0084-40d3-a866-5f95f14f8ab4)
![Screenshot 2023-06-21 at 15 01 13](https://github.com/rainstr7/blade-runners.game/assets/42678580/5657fe4f-f623-431b-a26d-0eae4a462a32)

### TBD (если есть)
Пришлось переписать немного роутеры

2023-06-21 17:46 UTC, KirGalkin commented on packages/client/src/components/RouterList/settings.tsx
> +  // '*': {
?

2023-06-21 17:47 UTC, KirGalkin commented on packages/client/src/hooks/useForum.ts
> +type Data = { data: ForumType | MessagesPayloadInterface; status: number }
надо yarn format, ну и не забывай про перенос строки

2023-06-21 17:47 UTC, KirGalkin commented on packages/client/src/hooks/useForum.ts
> +const useForum = () => {
а то в каше все

2023-06-21 17:49 UTC, KirGalkin commented on packages/client/src/views/Forum/DiscussPage/index.tsx
> +  useEffect(() => {
тоже все в куче

2023-06-22 05:07 UTC, rainstr7 commented on packages/client/src/hooks/useForum.ts
> +type Data = { data: ForumType | MessagesPayloadInterface; status: number }
я прогонял format, не очень понимаю что ты имеешь ввиду) прогнал еще раз все что он мне поправил в useForum это перенес одну строку
![Screenshot 2023-06-22 at 08 05 49](https://github.com/rainstr7/blade-runners.game/assets/42678580/b658fa04-a22f-4fd9-b262-68cb8b84540c)

2023-06-22 05:08 UTC, rainstr7 commented on packages/client/src/views/Forum/DiscussPage/index.tsx
> +  useEffect(() => {
тут вообще нет изменений после формата, хз что ты имеешь ввиду

2023-06-22 05:09 UTC, rainstr7 commented on packages/client/src/hooks/useForum.ts
> +const useForum = () => {
линтер все устраивает

2023-06-22 05:23 UTC, rainstr7 commented on packages/client/src/components/RouterList/settings.tsx
> +  // '*': {
тут да, я забыл раскомментить

2023-06-22 05:49 UTC, rainstr7 commented on packages/client/src/views/Forum/DiscussPage/index.tsx
> +  useEffect(() => {
перезалил с новыми изменениями после прогона линтера

2023-06-22 05:56 UTC, KirGalkin commented on packages/client/src/hooks/useForum.ts
> +type Data = { data: ForumType | MessagesPayloadInterface; status: number }
Не, я про то что лучше добавлять перенос строки 
например строки 23 24 явно лучше разделить строкой
import { EmojiClickData } from 'emoji-picker-react'
type Data = { data: ForumType | MessagesPayloadInterface; status: number }

VS

import { EmojiClickData } from 'emoji-picker-react'

type Data = { data: ForumType | MessagesPayloadInterface; status: number }

2023-06-22 05:56 UTC, KirGalkin approved these changes

2023-06-22 06:04 UTC, rainstr7 commented on packages/client/src/hooks/useForum.ts
> +type Data = { data: ForumType | MessagesPayloadInterface; status: number }
у меня просто такие щтуки стоят и я не вижу слипания 
![Uploading Screenshot 2023-06-22 at 09.03.35.png…]()

2023-06-22 15:02 UTC, kate-lozovaya requested changes

2023-06-22 15:34 UTC, rainstr7 commented on packages/client/src/views/Forum/DiscussPage/Message.tsx
> +  addEmoji: (emoji: EmojiClickData, id: string) => void
классный лайфхак спасибо этот интерфейс поправил

2023-06-22 15:36 UTC, rainstr7 commented on packages/client/src/views/Forum/DiscussPage/Time.tsx
> +  return <span> {normalizedTime}</span>
если про 13 строку то просмотрел просто, поправил

2023-06-22 15:44 UTC, rainstr7 commented on packages/client/src/views/Forum/DiscussPage/index.tsx
> +    setIsOpenEmoji(prevState => (+prevState === +id ? 0 : +id))
Да все верно, спасибо

2023-06-22 15:46 UTC, rainstr7 commented on packages/client/src/hooks/useForum.ts
> +    // const { status, data } = await request(getForumList)
я оставил потому что он как бы будет нужен (раскомменчен). Сейчас данные захардкожены как временное решение и я просто имитировал запрос, а в следующей итерации данные будем забирать из request из БД

2023-06-22 15:46 UTC, rainstr7 commented on packages/client/src/hooks/useForum.ts
> +      // const { status, data } = await request(getForumList, 'POST', body)
он еще пригодится

2023-06-22 15:47 UTC, rainstr7 commented on packages/client/src/hooks/useScore.ts
> +    player: object
да отличное замечание, надо взяться настроить прекоммит

2023-06-22 15:51 UTC, rainstr7 commented on packages/client/src/views/Forum/DiscussPage/index.tsx
> +  useEffect(() => {
я выше объяснил почему не заметил таких штук

2023-06-22 15:54 UTC, kate-lozovaya approved these changes

2023-06-22 15:54 UTC, kate-lozovaya commented on packages/client/src/views/Forum/DiscussPage/index.tsx
> +  useEffect(() => {
Да, прочитала.
Тут ничего не подписывается, поэтому мне было понятно, о чем KirGalkin

2023-06-23 06:08 UTC, merged