Bla 48
rainstr7/blade-runners.game pull request #38
Opened 2023-06-26 20:45 UTC by OvalniyKeks

Переключение тем (клиентская часть)

![image](https://github.com/rainstr7/blade-runners.game/assets/106172681/d2ab368f-9069-40bb-95c0-d811672da3ec)
![image](https://github.com/rainstr7/blade-runners.game/assets/106172681/9d93bdd3-a52f-47ee-9ff0-2f358fceb801)

2023-06-27 04:58 UTC, rainstr7 approved these changes
Отличная работа, у меня вопросов нет

2023-06-27 05:02 UTC, KirGalkin approved these changes

2023-06-27 14:48 UTC, kate-lozovaya commented
текст перекрывается картинкой

![image](https://github.com/rainstr7/blade-runners.game/assets/25737137/7ba9171e-2066-476a-8455-ee39b16db031)

2023-06-27 15:03 UTC, kate-lozovaya requested changes

2023-06-28 07:45 UTC, kate-lozovaya requested changes

2023-06-28 07:45 UTC, kate-lozovaya commented on packages/client/src/components/Theme/index.tsx
> +  const [theme, setTheme] = useState<Theme | null>(themes.dark);
[Исправление]
Тут больше не может быть `null`, его лучше убрать, тогда везде можно будет убрать проверку `theme?`

2023-06-28 07:45 UTC, kate-lozovaya commented on packages/client/src/views/Main/index.tsx
> +        <p style={{marginLeft: `${3}rem`}}>By Blade Runners</p>
[Исправление]
Картинка все равно выглядит как-то криво. И лучше не писать стили прямо в компоненте, у них слишком высокая специфичность, сложно будет что-то исправить, лучше делать класс
 
<img width="345" alt="image" src="https://github.com/rainstr7/blade-runners.game/assets/25737137/ebac73a3-7854-406d-998f-34b973fbe1e6">

2023-06-28 07:45 UTC, kate-lozovaya commented on packages/client/src/components/Theme/index.tsx
> +      <button className={`${cn.button} ${theme?.type === 'dark' ? cn.dark : cn.light}`} onClick={toggleTheme}></button>
Вот тут не ответил

2023-06-28 09:45 UTC, OvalniyKeks commented on packages/client/src/components/Theme/index.tsx
> +      <button className={`${cn.button} ${theme?.type === 'dark' ? cn.dark : cn.light}`} onClick={toggleTheme}></button>
Сделаю попозже, пока времени нет разбираться

2023-06-28 10:37 UTC, kate-lozovaya commented on packages/client/src/components/Theme/index.tsx
> +      <button className={`${cn.button} ${theme?.type === 'dark' ? cn.dark : cn.light}`} onClick={toggleTheme}></button>
Это несложно, просто создается объект, где ключи - тема, значение - класс

2023-06-28 10:39 UTC, kate-lozovaya approved these changes
Картинка все равно немного кривая. Это можешь поправить позже )

![image](https://github.com/rainstr7/blade-runners.game/assets/25737137/178287cc-5afd-479d-a1af-221c3981f1f4)

2023-06-28 14:52 UTC, merged