Bla 25
rainstr7/blade-runners.game pull request #6
Opened 2023-05-01 13:17 UTC by KirGalkin

**Реализация движка и основных механик игры**
- Управление игроком, прыжок
- Враги надвигаются на игрока
- Подсчет очков
- Скролл бэкграунда, для илюзии движения
- Столкновения
- Game over

**Скриншот**
<img width="914" alt="image" src="https://user-images.githubusercontent.com/124124244/235456675-60f7f337-cc06-41f0-9c35-9290eeff9cd5.png">

2023-05-02 06:56 UTC, rainstr7 commented on packages/client/src/core/Engine/index.tsx
> +}
Тут мне кажется можно упростить, что-то тяжеловато как-то читается. можно использовать деструкоризацию или вынести в переменные

2023-05-02 06:56 UTC, rainstr7 commented on packages/client/src/core/Engine/index.tsx
> +  if (keyCode && keyCode === 'Space') {
keyCode разве возвращает не  код т.е. number?
![Screenshot 2023-05-02 at 09 38 07](https://user-images.githubusercontent.com/42678580/235596899-6f985891-6341-4a92-acee-697903ab1b06.png)

2023-05-02 06:56 UTC, rainstr7 commented on packages/client/src/core/Engine/index.tsx
> +      lastTime = timeStamp;
из useEffect менять значение внешней переменной  lastTime в компоненте как мне кажется не очень хорошая идея. При render она будет перетераться на 0, нужно сделать или состояние или завести для нее ref

2023-05-02 06:56 UTC, rainstr7 commented on packages/client/src/hooks/useEvent.ts
> +export default useEvent
Хорошее решение вынести в хук добавление/удаление слушателя

2023-05-02 17:01 UTC, rainstr7 commented on packages/client/src/core/Engine/index.tsx
> +  if (keyCode && keyCode === 'Space') {
https://react.dev/reference/react-dom/components/common#handling-keyboard-events

2023-05-02 17:08 UTC, rainstr7 commented on packages/client/src/core/Engine/index.tsx
> +  if (keyCode && keyCode === 'Space') {
![Uploading Screenshot 2023-05-02 at 20.07.09.png…]()

2023-05-02 17:09 UTC, rainstr7 commented on packages/client/src/core/Engine/index.tsx
> +  if (keyCode && keyCode === 'Space') {
![Screenshot 2023-05-02 at 20 07 09](https://user-images.githubusercontent.com/42678580/235736190-7c88b28e-1565-4810-a569-6b919db03ba8.png)

2023-05-02 17:35 UTC, KirGalkin commented on packages/client/src/core/Engine/index.tsx
> +  if (keyCode && keyCode === 'Space') {
> а почему тогда не забирать по ключу code просто? e.code?

Я это и делаю) только предварительно кастю к KeyboardEvent, тк useEvent принимает просто Event
const keyCode = (e as KeyboardEvent)?.code;

Или я не понял коммента?

2023-05-02 17:58 UTC, KirGalkin commented on packages/client/src/core/Engine/index.tsx
> +}
на счет деструктуризации не понял чем может упростить, но в переменные вынес

2023-05-02 17:59 UTC, KirGalkin commented on packages/client/src/core/Engine/index.tsx
> +      lastTime = timeStamp;
Заюзал useRef, а вот с setState чтото не вышло, всегда 0 получал:(

2023-05-03 05:11 UTC, rainstr7 commented on packages/client/src/core/Engine/index.tsx
> +  if (keyCode && keyCode === 'Space') {
не - это я натупил ссорян )

2023-05-03 05:20 UTC, rainstr7 approved these changes
Отличная работа! Я даже поиграл)

2023-05-03 05:20 UTC, rainstr7 commented on packages/client/src/core/Engine/index.tsx
> +}
const {x, y, width, height} = enemy вот деструкоризация) тут конечно два объекта player и enemy поэтому не очень удобно было бы наверное деструктурировать или только один из объектьов. Все ок.

2023-05-04 11:20 UTC, hypnot1z commented on packages/client/src/core/Engine/index.tsx
> +  if (keyCode && keyCode === 'Space') {
На данном этапе разрешение, думаю, стоит поставить 1366х768 (самое распространенное)

2023-05-04 11:25 UTC, hypnot1z approved these changes
Очень круто.

2023-05-04 12:55 UTC, KirGalkin commented on packages/client/src/core/Engine/index.tsx
> +  if (keyCode && keyCode === 'Space') {
> На данном этапе разрешение, думаю, стоит поставить 1366х768 (самое распространенное)

надо будет адаптивно сделать, чтобы автоматом вычислялись размеры

2023-05-04 13:42 UTC, kate-lozovaya requested changes

2023-05-04 13:42 UTC, kate-lozovaya commented on packages/client/src/core/Engine/index.tsx
> +  const playerTopYPos = player.y
[Предложение]
Не очень нравятся названия, они длинные и трудночитаемы. Кажется, если это будут `playerTop` и `playerLeft`, то суть все равно будет понятна.

И может написать функцию, которая возвращает значения для любого объекта с `x`, `y`, `width`, `height`, которая подойдет и для `player` и для `enemy`.
```
function calcPosition<T extends { x: number; y: number; height: number; width: number }>(rect: T) {
    const { x, y, height, width } = rect;
    return {
        top: y,
        bottom: y + height,
        left: x,
        right: x + width,
    };
}
```

И тут брать результат выполнения:
```
const {top: playerTop, ...} = calcPosition(player);
const {top: enemyTop, ...} = calcPosition(enemy);
```

2023-05-04 13:42 UTC, kate-lozovaya commented on packages/client/src/core/Engine/index.tsx
> +    enemies.push(new Enemy(gameWidth, gameHeight,50, 50, 5));
[Исправление]
Не хватает пробела, прогони линтер и преттир

2023-05-04 13:42 UTC, kate-lozovaya commented on packages/client/src/core/enemy.ts
> +      this.markForDelete = true;
[Вопрос]
Уверен насчет названия? Кажется, сам класс враг не должен знать, что его удалят. 
Может сделать метод для проверки, что он вышел за границы экрана?

2023-05-04 13:42 UTC, kate-lozovaya commented on packages/client/src/core/Engine/index.tsx
> +
[Предложение]
Все, что написано выше этой строки тянет на отдельный класс.
Предлагаю вынести в отдельный ts файл

2023-05-04 13:45 UTC, kate-lozovaya commented
По формату комментов. Использую [Исправление], [Предложение], [Вопрос]
[Исправление] пишу там, где прям очень хочется увидеть исправление, но всегда можно все обсудить )

И хочется увидеть после ревью обработку каждого коммента от тебя. Можно писать текстом, можно ставить смайлики, резолвить мне удобнее самой, чтобы пройтись глазами, и посмотреть на код еще раз.

2023-05-04 17:28 UTC, KirGalkin commented on packages/client/src/core/enemy.ts
> +      this.markForDelete = true;
Согласен, нэйминг совсем неудачный. Можно вынести в целом, но я пока просто переименовал на isAlive. Так вроде все получается в своей зоне отвественности

2023-05-04 19:37 UTC, kate-lozovaya approved these changes
👍

2023-05-04 19:37 UTC, kate-lozovaya commented on packages/client/src/core/engine.ts
> +      // }
[Вопрос]
Не нужно ли убрать этот комментарий?

2023-05-05 06:16 UTC, merged